### ISSUE TITLE
Problem in RTL layout

### ISSUE THREAD

**Issue by MR62** [juanlabrador/BadgeCounter#2]
Hi,
I am new in android and I have a problem with BadgeCounter. When I set android:supportsRtl="true" and in main MainActivity write below code BadgeCounter don't  show icon with badge and there is blank space.

 if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.JELLY_BEAN_MR1) {
            getWindow().getDecorView().setLayoutDirection(View.LAYOUT_DIRECTION_RTL);
        }

How can I fix this problem?
Thanks in advance

**Comment by juanlabrador** [comment]
Hello, I have not given support again due to lack of time, but you can use this alternative, thanks for use mine https://github.com/mikepenz/Android-ActionItemBadge, maybe later I can update again.
